# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- develop

pool:
  name: "KinsonDigital"

variables:
  solution: "**/*.sln"
  projectName: "PluginSystem"
  buildPlatform: "x64"
  buildConfiguration: "Debug-SDL"
  unitTestBuildConfiguration: "Debug"
  netSDKVersion: "3.0.100-preview7-012821"
  unitTestProjectDir: "PluginSystem.Tests"

steps:
- task: NuGetToolInstaller@1
  displayName: "Use Nuget 5.2.0"
  inputs:
    versionSpec: 5.2.0

- task: UseDotNet@2
  displayName: "Use DotNet SDK 2.2.x"
  inputs:
    version: 2.2.x
    installationPath: "$(Agent.ToolsDirectory)/dotnet"

- task: NuGetCommand@2
  displayName: "Nuget Restore"
  inputs:
    command: restore

- task: VSBuild@1
  displayName: "Build PluginSystem Project"
  inputs:
    solution: "**/$(projectName)/*.csproj"
    platform: "$(buildPlatform)"
    configuration: "$(buildConfiguration)"

- task: UseDotNet@2
  displayName: "Use DotNet SDK 3.0.100 Preview 7"
  inputs:
    version: $(netSDKVersion)
    includePreviewVersions: true
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: VSBuild@1
  displayName: "Build Plugin System Unit Testing Project"
  inputs:
    platform: "$(buildPlatform)"
    configuration: "$(unitTestBuildConfiguration)"
    solution: "**/$(unitTestProjectDir)/*.csproj"
    vsVersion: latest

# - task: DotNetCoreCLI@2
#   displayName: "Run Unit Tests"
#   inputs:
#     command: test
#     projects: "**/$(unitTestProjectDir)/*.csproj"
#     arguments: "--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura"

# - script:
#   enabled: false
#   displayName: "Install & Run Report Generator"
#   dotnet tool install -g dotnet-reportgenerator-globaltool reportgenerator -reports:$(Build.SourcesDirectory)/$(unitTestProjectDir)/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/$(unitTestProjectDir) -reporttypes:HtmlInline_AzurePipelines;Cobertura