trigger:
  branches:
    include:
    - develop # Development Environment
    - master # Production Environment


variables:
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'any'
- name: buildConfiguration
  ${{ if notIn(variables['Build.SourceBranchName'], 'develop', 'master')}}:
    value: 'Debug'
  ${{ if eq(variables['Build.SourceBranchName'], 'develop')}}:
    value: 'Debug'
  ${{ if eq(variables['Build.SourceBranchName'], 'master')}}:
    value: 'Release'
- name: projectName
  value: 'ScorpionEngine'
- name: kinsonDigitalNugetFeed
  value: '1020f331-f22a-4330-a69a-78abfe6f6372/4c644bf2-f1e8-4f28-a3df-3bc9d3283df9'    
- name: pool
  value: 'Build-Release-Servers'




stages:
- stage: 'Main_Stage'
  displayName: 'Main Stage'
  pool: '$(pool)'
  jobs:
  - job: 'Build_ScorpionEngine_Job'
    displayName: 'Build Scorpion Engine'
    steps:
    - template: templates/build-tasks-template.yml
      parameters:
        projectName: $(projectName)
        buildPlatform: $(buildPlatform)
        buildConfiguration: $(buildConfiguration)
        vstsFeed: '$(kinsonDigitalNugetFeed)'


  - job: 'Run_ScorpionEngine_Tests_Job'
    displayName: 'Run Scorpion Engine Tests'
    steps:
    - template: templates/test-tasks-template.yml
      parameters:
        projectName: $(projectName)
        buildPlatform: $(buildPlatform)      
        buildConfiguration: $(buildConfiguration)
        vstsFeed: '$(kinsonDigitalNugetFeed)'


  - job: 'Publish_ScorpionEngine_Artifacts_Job'
    displayName: 'Publish Scorpion Engine Artifacts'
    steps:
    - template: templates/publish-tasks-template.yml
      parameters:
        projectName: $(projectName)
        buildPlatform: $(buildPlatform)
        buildConfiguration: $(buildConfiguration)
        vstsFeed: '$(kinsonDigitalNugetFeed)'
